/* =========================================
   ARCO — Project Data
   ========================================= */

const CATEGORIES = {
  amo: {
    id: 'amo',
    label: 'AMO',
    fullLabel: 'Assistance à Maîtrise d\'Ouvrage',
    cssClass: 'amo',
    color: '#0055B3'
  },
  sensibilisation: {
    id: 'sensibilisation',
    label: 'Sensibilisation',
    fullLabel: 'Sensibilisation',
    cssClass: 'sensi',
    color: '#9A6E00'
  },
  architecture: {
    id: 'architecture',
    label: 'Architecture',
    fullLabel: 'Architecture',
    cssClass: 'archi',
    color: '#1A7A38'
  },
  urbanisme: {
    id: 'urbanisme',
    label: 'Urbanisme culturel',
    fullLabel: 'Urbanisme culturel',
    cssClass: 'urba',
    color: '#C04000'
  }
};

const projects = [

  /* ===========================
     AMO
     =========================== */
  {
    id: 'amo-ecole-caumont',
    category: 'amo',
    title: 'École',
    location: 'Caumont sur Aure',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-tennis-blonville',
    category: 'amo',
    title: 'Tennis couvert',
    location: 'Blonville sur Mer',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-local-touffreville',
    category: 'amo',
    title: 'Local communal',
    location: 'Touffreville',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-saintgatien',
    category: 'amo',
    title: 'Un nouvel espace associatif et une nouvelle bibliothèque',
    location: 'Saint Gatien des Bois (14)',
    year: '2026',
    mission: 'Programmation, estimatifs sommaires, étude de faisabilité pour le CAUE 14',
    mo: 'Ville de Saint Gatien des Bois (14)',
    budget: null,
    partners: 'CAUE 14',
    description: 'Mission de programmation pour la transformation d\'un local communal en espace associatif et bibliothèque, incluant estimatifs sommaires et étude de faisabilité.',
    images: []
  },
  {
    id: 'amo-logement-valorbiquet',
    category: 'amo',
    title: 'Logement',
    location: 'Valorbiquet',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-refectoire-ablon',
    category: 'amo',
    title: 'Réfectoire scolaire → médiathèque / fablab',
    location: 'Ablon',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-foyer-saintandre',
    category: 'amo',
    title: 'Foyer de vie',
    location: 'Saint André sur Orne',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-erp-honfleur',
    category: 'amo',
    title: 'Accessibilité ERP gymnase',
    location: 'Honfleur',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-atelier-hebertot',
    category: 'amo',
    title: 'Atelier communal',
    location: 'Saint André d\'Hébertot',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-logement-creully',
    category: 'amo',
    title: 'Logement d\'urgence',
    location: 'Creully',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-mediatheque-bretteville',
    category: 'amo',
    title: 'Médiathèque',
    location: 'Bretteville sur Laize',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-scop-bretteville',
    category: 'amo',
    title: 'SCOP Bouchard – Tiers lieu',
    location: 'Bretteville sur Laize',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-presbytere-annebault',
    category: 'amo',
    title: 'Logement – Rénovation presbytère',
    location: 'Annebault',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-local-cambes',
    category: 'amo',
    title: 'Local communal',
    location: 'Cambes en Plaine',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-mairie-juvigny',
    category: 'amo',
    title: 'Mairie',
    location: 'Juvigny sur Seulles',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-mairie-stdenis',
    category: 'amo',
    title: 'Mairie + logement',
    location: 'St Denis de Mailloc',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-local-manneville',
    category: 'amo',
    title: 'Local communal + mairie',
    location: 'Manneville la Pipard',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-sante-manneville',
    category: 'amo',
    title: 'Pôle santé',
    location: 'Manneville la Pipard',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-sante-subles',
    category: 'amo',
    title: 'Pôle santé',
    location: 'Subles',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-bib-clecy',
    category: 'amo',
    title: 'Bibliothèque / OT / Musée',
    location: 'Clécy',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-mairie-manvieux',
    category: 'amo',
    title: 'Mairie',
    location: 'Manvieux',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'amo-logements-marguerite',
    category: 'amo',
    title: 'Logements seniors',
    location: 'Sainte Marguerite d\'Elle',
    year: null,
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },

  /* ===========================
     SENSIBILISATION
     =========================== */
  {
    id: 'sensi-joliot-blainville',
    category: 'sensibilisation',
    title: 'Sensibilisation des jeunes à l\'école Joliot Curie',
    location: 'Blainville sur Orne (14)',
    year: '2025–2026',
    mission: 'Animation d\'ateliers avec l\'équipe d\'élus, l\'équipe pédagogique et l\'inspection académique. Ateliers dans 2 classes primaires. Restitution et création d\'un cahier des charges dans le cadre de l\'appel à idées #6 « La classe, mon école » lancé par le CAUE 14.',
    mo: null,
    budget: null,
    partners: 'CAUE 14',
    description: 'Appel à idées – sensibilisation des jeunes à l\'architecture et recueil de leur vision de leur école en tant qu\'usagers.',
    images: []
  },
  {
    id: 'sensi-7collines-blangy',
    category: 'sensibilisation',
    title: 'École 7 collines – Appel à Idées',
    location: 'Blangy le Château',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'sensi-yvonne-thaon',
    category: 'sensibilisation',
    title: 'École Yvonne Guégan – Appel à Idées',
    location: 'Thaon',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'sensi-ateliers-maquette',
    category: 'sensibilisation',
    title: 'Ateliers maquette avec des élémentaires',
    location: null,
    year: '2014–2016',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'sensi-vacances-utiles',
    category: 'sensibilisation',
    title: 'Vacances utiles',
    location: 'Lima',
    year: '2013–2023',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Asso MAM Lima',
    description: null,
    images: []
  },
  {
    id: 'sensi-skate-lima',
    category: 'sensibilisation',
    title: 'Fabrication de skate',
    location: 'Lima',
    year: '2015',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Asso MAM Lima',
    description: null,
    images: []
  },
  {
    id: 'sensi-patrimoine',
    category: 'sensibilisation',
    title: 'Enfants du patrimoine',
    location: 'Caen (14)',
    year: '2021–2024',
    mission: 'Visite de la bibliothèque Alexis de Tocqueville pour élémentaires.',
    mo: null,
    budget: null,
    partners: 'CAUE',
    description: null,
    images: []
  },
  {
    id: 'sensi-reconstruction-vire',
    category: 'sensibilisation',
    title: 'L\'architecture de la reconstruction',
    location: 'Vire',
    year: '2023',
    mission: 'Visite grand public.',
    mo: null,
    budget: null,
    partners: 'CAUE Vire',
    description: null,
    images: []
  },
  {
    id: 'sensi-reemploi',
    category: 'sensibilisation',
    title: 'Sensibilisation au réemploi',
    location: 'Normandie / Angers / Allemagne',
    year: '2025',
    mission: 'Visite du plateau circulaire, visite d\'Emmaüs à Angers, rencontre du réemploi en Normandie, superette en Allemagne.',
    mo: null,
    budget: null,
    partners: 'CAUE',
    description: null,
    images: []
  },
  {
    id: 'sensi-gemdev',
    category: 'sensibilisation',
    title: 'GEMdev',
    location: 'Lima',
    year: '2020–2024',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'sensi-parque-lima',
    category: 'sensibilisation',
    title: 'Mi parque es tu parque',
    location: 'Lima',
    year: '2013',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Asso MAM Lima',
    description: null,
    images: []
  },
  {
    id: 'sensi-seminario-octava',
    category: 'sensibilisation',
    title: 'Seminario vivenciales',
    location: 'Lima',
    year: '2023–2024',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Octava Lima',
    description: null,
    images: []
  },
  {
    id: 'sensi-carton',
    category: 'sensibilisation',
    title: 'El Carton',
    location: null,
    year: '2007–2012',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'sensi-savoirs-lycee',
    category: 'sensibilisation',
    title: 'Savoir d\'usage et savoir faire',
    location: 'Franqueville Saint Pierre',
    year: '2024',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Lycée Franqueville Saint Pierre, ENSA Normandie',
    description: null,
    images: []
  },
  {
    id: 'sensi-urbanisme-caen',
    category: 'sensibilisation',
    title: 'Histoire de l\'urbanisme, dynamique et stratégie urbaine',
    location: 'Caen',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Université de Caen',
    description: null,
    images: []
  },
  {
    id: 'sensi-barrio-pucp',
    category: 'sensibilisation',
    title: 'Barrio y espacio publico en el habitat popular',
    location: 'Lima',
    year: '2023',
    mission: null,
    mo: null,
    budget: null,
    partners: 'PUCP, MAM',
    description: null,
    images: []
  },
  {
    id: 'sensi-construccion-pucp',
    category: 'sensibilisation',
    title: 'Seminario Construcción 1:1 – Los Jazmines',
    location: 'Lima',
    year: '2024',
    mission: 'Atelier ouvert aux étudiants en architecture.',
    mo: null,
    budget: null,
    partners: 'PUCP, MAM',
    description: null,
    images: []
  },

  /* ===========================
     ARCHITECTURE
     =========================== */
  {
    id: 'archi-maison-verrieres',
    category: 'architecture',
    title: 'Maison individuelle ossature bois bioclimatique',
    location: 'Verrières le Buisson (91)',
    year: '2010',
    mission: 'Mission complète de maîtrise d\'œuvre',
    mo: 'Particulier',
    budget: null,
    partners: null,
    description: 'Maison ossature bois 145 mm d\'épaisseur avec isolation en ouate de cellulose projetée dans l\'ossature et fibre de bois en isolation par l\'extérieur. Menuiseries en bois-aluminium, vitrage faible émissivité, volets roulants sur toutes les baies. Plancher chauffant sur 2 niveaux alimenté par une pompe à chaleur géothermique à captage vertical. VMC double flux avec by-pass. Toiture végétalisée pour limiter le débit des eaux pluviales et réduire l\'albédo.',
    images: []
  },
  {
    id: 'archi-kine-verrieres',
    category: 'architecture',
    title: 'Cabinet de kinésithérapie',
    location: 'Verrières le Buisson (91)',
    year: '2013',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-hotel-verrieres',
    category: 'architecture',
    title: 'Hôtel – aménagement des combles',
    location: 'Verrières le Buisson (91)',
    year: '2014',
    mission: 'Utilisation des combles pour la création de 14 chambres dont 2 PMR.',
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-piscine-verrieres',
    category: 'architecture',
    title: 'Piscine en sous-sol',
    location: 'Verrières le Buisson (91)',
    year: '2019',
    mission: null,
    mo: 'Particulier',
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-gite-feuguerolles',
    category: 'architecture',
    title: 'Aménagement du gîte',
    location: 'Feuguerolles Bully (14)',
    year: '2020',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-piscine-feuguerolles',
    category: 'architecture',
    title: 'Projet de piscine extérieure',
    location: 'Feuguerolles Bully (14)',
    year: '2021',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-appart1-caen',
    category: 'architecture',
    title: 'Rénovation appartement 1',
    location: 'Caen (14)',
    year: '2022',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-appart2-caen',
    category: 'architecture',
    title: 'Rénovation appartement 2',
    location: 'Caen (14)',
    year: '2023',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-caue-caen',
    category: 'architecture',
    title: 'Bureaux du CAUE',
    location: 'Caen (14)',
    year: '2023',
    mission: null,
    mo: 'CAUE 14',
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-escalier-dordogne',
    category: 'architecture',
    title: 'Escalier château',
    location: 'Dordogne',
    year: '2025',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-ferme-herblay',
    category: 'architecture',
    title: 'Rénovation ferme 1850 + remise',
    location: 'Herblay sur Seine',
    year: '2024–2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-maison-desert',
    category: 'architecture',
    title: 'Maison dans le désert – brique BTC',
    location: 'Paracas, Pérou',
    year: '2020–2024',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-casa-solano',
    category: 'architecture',
    title: 'Casa Solano',
    location: 'Barranco, Lima',
    year: '2023',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-appart-jesus',
    category: 'architecture',
    title: 'Rénovation appartement',
    location: 'Jesus Maria, Lima',
    year: '2018',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-maison-arts',
    category: 'architecture',
    title: 'Rénovation maison des arts',
    location: 'Dordogne',
    year: '2017',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-local-lima',
    category: 'architecture',
    title: 'Local communal, bibliothèque, bureaux',
    location: 'Lima, Pérou',
    year: '2012–2024',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Mano a Mano',
    description: null,
    images: []
  },
  {
    id: 'archi-jardins-bazarnaom',
    category: 'architecture',
    title: 'Jardins Bazarnaom',
    location: 'Caen Presqu\'île',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-cuisine-bernieres',
    category: 'architecture',
    title: 'Cuisine sur jardin',
    location: 'Bernières sur Mer',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-maison-ouistreham',
    category: 'architecture',
    title: 'Aménagement maison',
    location: 'Ouistreham',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'archi-casa-mauro',
    category: 'architecture',
    title: 'Casa Mauro',
    location: 'Tacna, Pérou',
    year: '2021',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },

  /* ===========================
     URBANISME CULTUREL
     =========================== */
  {
    id: 'urba-parcs-lima',
    category: 'urbanisme',
    title: 'Parcs urbains (18 parcs)',
    location: 'Lima, Pérou',
    year: '2012–2024',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Asso MAM Lima',
    description: null,
    images: []
  },
  {
    id: 'urba-zorrito',
    category: 'urbanisme',
    title: 'Zorrito runrunteca',
    location: 'Lima, Pérou',
    year: '2023',
    mission: 'Mission complète de maîtrise d\'œuvre',
    mo: 'Ministère de la Culture péruvien',
    budget: null,
    partners: 'Octava',
    description: 'Ce projet se développe dans le quartier de Barrios Altos dans le centre de Lima. Réalisé avec le ministère de la Culture péruvien dans le cadre du programme « Renovarte », il a permis de construire, avec les habitants, une sculpture de bibliothèque publique valorisant la mémoire locale à partir de matériaux de récupération.',
    images: [
      'media/photos/Zorrito/6. OCTAVA – Contes urbains.jpg',
      'media/photos/Zorrito/7. OCTAVA – Contes urbains.jpg',
      'media/photos/Zorrito/8. OCTAVA – Contes urbains.jpg',
      'media/photos/Zorrito/9. OCTAVA – Contes urbains.jpg',
      'media/photos/Zorrito/10. OCTAVA – Contes urbains.jpg'
    ]
  },
  {
    id: 'urba-mirones',
    category: 'urbanisme',
    title: 'Muralisation Mirones',
    location: 'Lima, Pérou',
    year: '2016',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Homogeneos',
    description: null,
    images: []
  },
  {
    id: 'urba-eldorado-lille',
    category: 'urbanisme',
    title: 'El Dorado – Lille 3000 Festival',
    location: 'Lille',
    year: '2019',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Detonador',
    description: null,
    images: []
  },
  {
    id: 'urba-motor-humano',
    category: 'urbanisme',
    title: 'Motor Humano',
    location: 'Lima, Pérou',
    year: '2015–2019',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Detonador',
    description: null,
    images: []
  },
  {
    id: 'urba-amazonia',
    category: 'urbanisme',
    title: 'Amazonia aquí',
    location: 'Lima, Pérou',
    year: '2015',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Detonador',
    description: null,
    images: []
  },
  {
    id: 'urba-mondeville',
    category: 'urbanisme',
    title: 'Mondeville',
    location: 'Caen',
    year: '2026',
    mission: null,
    mo: null,
    budget: null,
    partners: null,
    description: null,
    images: []
  },
  {
    id: 'urba-memoria-lima',
    category: 'urbanisme',
    title: 'Parque de la memoria – El Brillante',
    location: 'Lima, Pérou',
    year: '2023',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Octava',
    description: null,
    images: []
  },
  {
    id: 'urba-piki',
    category: 'urbanisme',
    title: 'Piki',
    location: 'Lima, Pérou',
    year: '2024',
    mission: null,
    mo: null,
    budget: null,
    partners: 'Octava',
    description: null,
    images: []
  }
];

function getProject(id) {
  return projects.find(p => p.id === id) || null;
}

function getProjectsByCategory(cat) {
  return projects.filter(p => p.category === cat);
}
